from setuptools import setup

setup(name='openxai',
      version='0.1',
      description='A general-purpose lightweight library that provides a comprehensive list of functions to systematically benchmark explanations generated by attribute-based explanation methods.',
      packages=['openxai'],
      zip_safe=False)
